FROM golang:alpine AS builder
WORKDIR /api
COPY . /api
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" -o api ./cmd/api/api.go

FROM alpine:latest AS runner
WORKDIR /api
COPY --from=builder /api/api .
# timezone
ENV TZ $TZ
# install tzdata and font-noto-cjk and chromium
RUN apk add --no-cache tzdata font-noto-cjk chromium

EXPOSE 80

ENTRYPOINT ["./api"]